### ISSUE TITLE
Development announce

### ISSUE THREAD

**Issue by wsdjeg** [SpaceVim/org-mode#1]
Hi users:

I will create new plugin for org file. this plugin will be wroten in pure vim script with python dependency removed. and It will base on SpaceVim public API.

I will use the async vim func in neovim and the `nvim_*` func, this plugin will also support vim8, but you will get better experience in neovim.

I will release first alpha version of org-mode in Nov.

I will alse read the code of some existing plugin:

- https://github.com/jceb/vim-orgmode ( need python support)
- https://github.com/hsitz/VimOrganizer (last updating is three years ago)

**Comment by zhujinxuan** [comment]
Thanks a lot. I will join after the first dev/alpha version~

**Comment by wsdjeg** [comment]
@zhujinxuan thanks, the discussion is moved to https://github.com/SpaceVim/SpaceVim/issues/3793
